services:
  - type: web
    name: edubus-face-extraction
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind=0.0.0.0:$PORT --timeout 600 application:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
